FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*
ENV PYTHON=/usr/bin/python3
RUN pip3 install --upgrade pip && pip3 install requests flask
WORKDIR /app
COPY . /app
EXPOSE 5000
CMD ["$PYTHON", "app.py"]
