FROM ubuntu:20.04
WORKDIR /app
RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*
RUN pip3 install --upgrade pip && pip3 install requests flask
ENV PYTHONPATH=/app/script
COPY . /app
RUN python3 auto_gen_data_cache.py -f input.txt
EXPOSE 5000
CMD [python3, "app.py"]
