FROM ubuntu:16.04
ENV PYTHONPATH=/app
RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*
RUN pip3 install --upgrade pip && pip3 install requests flask
RUN python3 app.py