FROM ubuntu:20.04
RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*
ENV PYTHON=/usr/bin/python3
RUN pip install --no-cache-dir requests==2.22.0 beautifulsoup4==4.7.1
RUN ldconfig
WORKDIR /app
COPY . /app
EXPOSE 5000
CMD ["$PYTHON", "app.py"]