FROM alpine:3.8

# pkg-command依赖
RUN apt install wget
RUN wget http://ftp.gnu.org/gnu/gawk/gawk-5.1.0.tar.xz

# VarPSet-VarCSet依赖
RUN runDeps="$( \
        scanelf --needed --nobanner /usr/bin/ss-* \
            | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
            | xargs -r apk info --installed \
            | sort -u \
    )"


RUN apk add --no-cache --virtual .run-deps $runDeps


RUN aaa="123"
RUN echo $aaa > /etc/aaa.txt

# 目录依赖
RUN wget -q -nc --no-check-certificate -P /var/tmp https://cmake.org/files/v3.11/cmake-3.11.1-Linux-x86_64.sh
RUN /var/tmp/cmake-3.11.1-Linux-x86_64.sh --prefix=/usr/local --skip-license


RUN mkdir -p /var/tmp && touch 1.txt
RUN cd /var/tmp


# other依赖
RUN groupadd -g 1000 laradock && useradd -l -u 1000 -g laradock -m laradock -G docker_env && usermod -p "*" laradock -s /bin/bash
RUN chown laradock:laradock /home/laradock/aliases.sh
