FROM alpine:3.8

# RUN RUN
RUN apt install wget
RUN wget http://ftp.gnu.org/gnu/gawk/gawk-5.1.0.tar.xz

# COPY RUN
COPY ./gawk-5.1.0.tar.xz /usr/local/src/
RUN tar -xvf /usr/local/src/gawk-5.1.0.tar.xz -C /usr/local/src/