FROM node:8.9-alpine
ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG JENKINS_AGENT_HOME=/home/${user}

RUN groupadd -g ${gid} ${group} \
    && useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

ENV PATH /app/node_modules/.bin:$PATH

ARG PORT=9000
ENV PORT $PORT

ARG BUILD_AT=/app
WORKDIR ${BUILD_AT}

COPY . ${BUILD_AT}

CMD npm start